version: "3"

services:


  db:
    restart: unless-stopped
    image: postgres:15
    tmpfs: 
      - /tmp:size=100m
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  app: &base
    restart: unless-stopped
    image: harbor.yurusov.com/public/servers-com-test:${TAG-main}
    environment:
      - HANAMI_ENV=production
      - DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL=true

  worker: 
    <<: *base
    command: /bin/sh -c /app/docker/start_worker.sh


