version: "2.4"

services:

  db:
    restart: unless-stopped
    image: postgres:15
    tmpfs: /tmp
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes: 
      - /tmp:/var/lib/postgresql/data

  app:
    restart: unless-stopped
    image: harbor.yurusov.com/public/servers-com-test:${TAG-main}
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/servers_com_test


