name: Build

on:
  push:
    branches: [ main, development ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main, development ]

env:
  REGISTRY: harbor.yurusov.com
  IMAGE_NAME: public/servers-com-test
  COMPOSE_FILE: ./docker/tests/docker-compose.yml


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=ref,event=branch,suffix=-{{sha}}
            type=ref,event=tag,suffix=-{{sha}}
            type=semver,pattern={{version}}
            type=sha,prefix=

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          outputs: type=docker,dest=/tmp/docker-image.tar
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: /tmp/docker-image.tar

  rspec:

    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: docker-image
          path: /tmp

      - name: Load image
        run: |
          docker load --input /tmp/docker-image.tar
          docker image ls -a

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Start docker-compose and run rspec
        run: |
          docker-compose up -d db
          sleep 3
          docker-compose run app docker/wrap.sh rspec

  rubocop:

    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: docker-image
          path: /tmp

      - name: Load image
        run: |
          docker load --input /tmp/docker-image.tar
          docker image ls -a

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Start docker-compose and run rubocop
        run: |
          docker-compose run app bundle exec rubocop

      - name: Add code coverage comment
        uses: romeovs/lcov-reporter-action@v0.3.1 
        with:
          lcov-file: ./coverage/lcov/servers-com-test.lcov
          github-token: ${{ secrets.GITHUB_TOKEN }}

  push:

    runs-on: ubuntu-latest
    needs: rspec
    steps:

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: robot$github
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: docker-image
          path: /tmp

      - name: Load and push image
        run: |
          docker load --input /tmp/docker-image.tar
          docker push -a ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Clean up
        uses: geekyeggo/delete-artifact@v2
        with:
            name: docker-image


